[build-system]
requires = ["uv_build>=0.11.2,<0.12.0"]
build-backend = "uv_build"

[project]
name = "omnidep"
version = "0.3.10"
description = "Linter to compare project dependencies against imports in source code"
authors = [{name = "Steve Jessop", email = "68118527+sjjessop@users.noreply.github.com"}]
readme = "README.rst"
license = "MIT"
license-files = ["LICENSE"]
urls.Homepage = "https://github.com/sjjessop/omnidep"
urls.Changelog = "https://github.com/sjjessop/omnidep/tree/develop#changelog"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
scripts = {omnidep = "omnidep.main:script_entry_point"}
requires-python = ">=3.8.2"
dependencies = [
    "isort>=5.0.1 ; python_full_version < '3.10'",  # 5.0.1 fixes some issue importing vendored toml
    "tomli>=1.1.0 ; python_full_version < '3.11'",  # 1.1.0 adds support for binary filehandles
]

[dependency-groups]
dev = [
    "coverage[toml]>=7.6.1",
    "mypy>=1.14.1",
    "pytest>=8.3.5",
    "pytest-cov>=5.0.0",
    "ruff~=0.15.8",
]
test_case = [
    "cffi>=1.17.1",
    "opentelemetry-api>=1.33.1",
    "opentelemetry-sdk>=1.33.1",
    "pyOpenSSL>=26.0.0",
]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-name = ["omnidep"]
module-root = ""


[tool.omnidep]
local-test-paths = ["omnidep/tst/"]
ignore-imports = [
    # Used in test cases as a missing package/module
    "no_such_module",
    # Used in test cases as a namespace package
    "opentelemetry",
    # Omnidep does not understand version-specific imports
    "tomllib",
]


[tool.mypy]
pretty = true
strict = true
warn_unreachable = true
disallow_untyped_calls = false
overrides = [{module = "opentelemetry", ignore_missing_imports = true}]


[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
]


[tool.pytest.ini_options]
filterwarnings = ["error"]


[tool.ruff]
output-format = "full"
show-fixes = true
target-version = "py38"

[tool.ruff.lint]
select = [
    # isort
    "I001",
    # Old-school flake8 rules
    "E", "F",
    # Helpers for tedious admin
    "EXE", "INP", "YTT",
    # Coding style warts
    "A001", "A002", "C4", "ISC", "PTH", "RET", "RSE",
    # Potential code improvements
    "B", "C90", "FBT", "PGH", "PL", "PT", "RUF", "S", "UP"
]
ignore = [
    "B023",  # The problem is not the function definition, but escaped references.
    "C401",  # Writing set() to imply deduplication is clearer to me than just punctuation.
    "E501",  # I have a 4k display.
    "PLR0913",  # Restricts keyword-only arguments too much
    "PLR2004",  # Rejects too many innocuous numbers.
    "PTH201",  # Explicit is better than implicit, so allow Path('.')
]

[tool.ruff.lint.per-file-ignores]
"omnidep/tst/*" = [
    "S101",  # pytest expects asserts
]
"omnidep/tst/test_cases/*" = [
    "I001",  # test cases are all about the imports so they want them laid out.
]

[tool.ruff.lint.isort]
force-sort-within-sections = true
lines-after-imports = 1

[tool.ruff.lint.flake8-pytest-style]
parametrize-names-type = "csv"

[tool.ruff.lint.pyupgrade]
# While still supporting Python 3.8, avoids having different style requirements
# according to whether or not each file imports __future__ annotations.
keep-runtime-typing = true
