name: tests

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.7", "3.8", "3.9", "3.10"]
      fail-fast: false
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install code and dev dependencies
        run: |
          pip install poetry==1.1.13
          poetry install
          poetry run pip freeze

      - name: Lint
        run: |
          poetry run isort . --check-only
          poetry run flake8 .
          poetry run mypy .

      - name: Test
        run: poetry run pytest --cov=omnidep --cov-branch --cov-report=term --durations=3
