name: tests

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      fail-fast: false
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.3
        with:
          version: 1.2.2

      - name: Install project
        run: |
          poetry install
          poetry run pip freeze
          poetry run pip check

      - name: Lint
        run: |
          poetry run isort . --check-only
          poetry run flake8 .
          poetry run mypy .

      - name: Test
        run: poetry run pytest --cov=omnidep --cov-branch --cov-report=term --durations=3

      - name: Install minimal dependencies
        run: |
          poetry run pip install tomli==1.1.0
          poetry run pip install importlib-metadata==1.1.0
          poetry run pip install isort==5.0.1
          poetry run pip freeze
          poetry run pip check

      - name: Test minimal dependencies
        run: poetry run pytest --durations=3
